In [66]:
import pandas as pd

In [67]:
data = pd.read_csv('weight-height.csv')

In [68]:
data.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [98]:
X = data[['Height', 'Gender_Male']]
y = data['Weight']

In [83]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2
)

In [85]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [86]:
y_pred = model.predict(X_test)

In [88]:
print(data.dtypes)

Height         float64
Weight         float64
Gender_Male       bool
dtype: object

In [89]:
data

         Height      Weight  Gender_Male
0     73.847017  241.893563         True
1     68.781904  162.310473         True
2     74.110105  212.740856         True
3     71.730978  220.042470         True
4     69.881796  206.349801         True
...         ...         ...          ...
9995  66.172652  136.777454        False
9996  67.067155  170.867906        False
9997  63.867992  128.475319        False
9998  69.034243  163.852461        False
9999  61.944246  113.649103        False

[10000 rows x 3 columns]

In [110]:
def pred_weight(height, gender):
    sample = pd.DataFrame({
        'Height': [height],
        'Gender_Male': [gender]
    })

    prediction = model.predict(sample)

    lbs = prediction[0]
    kg = lbs * 0.453592

    print(f"Predicted Weight: {kg:.2f} kg")

In [112]:
feet = int(input("Enter feet: "))
inches = int(input("Enter inches: "))

height_inches = feet * 12 + inches

gender = input("Enter Gender (Male/Female): ").strip().lower()

if gender == "male":
    gender = True
elif gender == "female":
    gender = False
else:
    print("Invalid gender! Please enter Male or Female.")
    exit()

pred_weight(height_inches, gender)

Enter feet:  6
Enter inches:  3
Enter Gender (Male/Female):  Female

Predicted Weight: 92.25 kg

In [113]:
from sklearn.metrics import r2_score

y_pred = model.predict(X_test)
print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.9037416940055818

In [114]:
pred_weight(75, True)   # Male
pred_weight(75, False)  # Female

Predicted Weight: 101.01 kg
Predicted Weight: 92.25 kg